### ISSUE TITLE
Naming: Http3Transport should be HTTP3Transport

### ISSUE THREAD

**Issue by annevk** [WICG/web-transport#110]
As per https://w3ctag.github.io/design-principles/#casing-rules.

However, it seems like a bad precedent to include the protocol version number in an API.

**Comment by cynthia** [comment]
Yes, and yes.

**Comment by vasilvv** [comment]
Since we've renamed the API class to `WebTransport` in #134, closing this as moot.

**Comment by annevk** [comment]
Thanks, that does seem a whole lot better.
