### ISSUE TITLE
"server_certificate_fingerprints" unusually named

### ISSUE THREAD

**Issue by ricea** [WICG/web-transport#120]
My impression is that names_with_underscores aren't usually used in the web platform. Should this be "serverCertificateFingerprints"? Or would just "fingerprints" be sufficiently unambiguous?

**Comment by ricea** [comment]
Also `options` is a much more common name than `config` in the web platform, so the dictionary should probably be called QuicTransportOptions.

**Comment by vasilvv** [comment]
Yeah, I think we should rename it to camelCase.  Re `config`, I think I called it Configuration because that's what WebRTC calls it, though I agree that `options` might be better.
