### ISSUE TITLE
Consider adding support for certificates not anchored to Web PKI

### ISSUE THREAD

**Issue by vasilvv** [WICG/web-transport#18]
I've been talking to some folks who are currently using RTC Data Channels but are interested in using WebTransport.  One of the use cases that came up is a situation where a website spins up an ephemeral VM and wants the user to talk to that VM directly.  Provisioning a real browser-trusted certificate can be a lot of pain in this scenario.  If we don't provide a way to deal with this, we'd regress over what the Data Channels currently provide.

We can do this with QuicTransport, since the API we designed is sufficiently low-level, i.e. we don't risk accidentally leaking the channel with altered trust model into random parts of the web ecosystem; nor do we send any sensitive data like cookies as the part of the handshake.

I've thought about this a bunch, and my current conclusion is that the best way to do this would be to essentially copy the WebRTC mechanism where you just specify the expected certificate hash.  Here are some alternatives, and why I believe they are bad:

* **Allowing users to just ignore the certificate**.  This is bad in an obvious way: it encourages users to not do any authentication at all, steering them towards bad practices.  It's also bad in a non-obvious way: if the users do decide to do their own authentication, they would have to bind the underlying cryptographic channel to it, which would require us to support TLS secret exporters.
* **Allowing users to have a custom certificate callback**.  This was my original instinct, however, on the reflection, I am not quite happy with it.  My main concern is that QUIC connections can be intercepted by an enterprise MITM firewall, and the certificate in that firewall could contain potentially sensitive information.

**Comment by pthatcherg** [comment]
I agree that this is a valuable use, and some people have told me they'd prefer to use the p2p version of WebTransport (RTCQuicTransport + RTCIceTransport) specifically to able to do this (even though they then have to also do ICE on the server).  

One easy solution is to pull the certificate-related portions of the p2p RTCQuicTransport over to be usable from the client/server QuicTransport, but without requiring ICE.  And I think that's what you are suggesting.

**Comment by Atrius** [comment]
I'd also like to see the WebRTC auth mechanism for p2p auth in WebTransport, preferably including client authentication, which IIRC is missing from/not implemented yet in RTCQuicTransport.

I'm not too sure if there's a use-case for client auth in the client/server case.  But we definitely need it for p2p auth, and it seems kind of silly to force a server that wants that feature to use ICE just so it can authenticate its client.
