### ISSUE TITLE
Provide a way to specify a subprotocol in client-server

### ISSUE THREAD

**Issue by vasilvv** [WICG/web-transport#26]
WebSockets have a subprotocol mechanism which works similar to ALPN (see https://tools.ietf.org/html/rfc6455#section-1.9).  Perhaps we should provide web applications using this API the same functionality directly via ALPN, e.g., if the client asks for "foo" and "bar", we provide ALPNs "wq:foo" and "wq:bar".

**Comment by pthatcherg** [comment]
Notes from a discussion:

Why a URL 3rd parameter? A place for CSP.  Why?  Because CSP is based on URLs.  

Why not a 3rd parameter on QuicTransport? The JS/wasm can always do that anyway, perhaps when they do auth (so it might not be so onerous)

Why not 3rd parameter URL? A lot of things will expect it's an HTTP request, and we don't want to deal with cookies and storage.


Alternative: use "quic://$host:$port"

**Comment by vasilvv** [comment]
> Why not a 3rd parameter on QuicTransport? The JS/wasm can always do that anyway, perhaps when they do auth (so it might not be so onerous)

So, I thought about this for a while, and I think I am currently leaning towards "add 3rd parameter" option.

From the design standpoint, our general goal has been roughly "provide the feature set one would get from using QUIC directly, but not more".  So, for instance this principle bars cookies and HTTP auth, as QUIC by itself does not support those; but it does not preclude us from authenticating the server using WebPKI (in fact, we require that) or authenticating the client using a TLS certificate (we currently do not support that, but I do not see that much of a problem of supporting that if there are users who want that).

Multiplexing here is interesting because QUIC does support "third parameter" natively via ALPN, but we require ALPN to be fixed because of security restrictions.  Thus, I feel like we should provide a replacement mechanism for this.  The two options we've discussed so far are:

1. Transmitting it as an ALPN suffix.
1. Transmitting it together with origin on special stream.

I think the second option is preferable because then it gets encrypted.
