### ISSUE TITLE
"resolve" or "fulfill" a promise

### ISSUE THREAD

**Issue by pthatcherg** [WICG/web-transport#29]
Ah, promises.... your terminology is so confusing.  Should we say "resolve" a promise or "fulfill" a promise?

Reading these docs:

https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md
https://stackoverflow.com/questions/29268569/what-is-the-correct-terminology-for-javascript-promises

may leave you tending toward "fulfill".

But a sampling of recent web specs shows almost all of them using only "resolve":

https://www.w3.org/TR/2018/WD-wasm-web-api-1-20180904/
https://www.w3.org/TR/2018/CR-webrtc-stats-20180703/
https://www.w3.org/TR/2018/WD-clipboard-apis-20181108/
https://www.w3.org/TR/2018/WD-push-api-20181026/
https://www.w3.org/TR/2018/WD-screen-orientation-20181012/

But at least one is using the word "fulfilment":

https://www.w3.org/TR/2018/WD-web-animations-1-20181011/

And WebRTC uses "resolve" (~20 times) and "fulfillment" (~10 times) and "fulfill" once:

https://www.w3.org/TR/2018/CR-webrtc-20180927/

Perhaps the right words are "resolve" and "fulfillment"?

**Comment by domenic** [comment]
Rule of thumb: resolve is the verb, and fulfilled is the adjective.

(Resolved can also be an adjective, but it is a less useful one, since a resolved promise can be in any of the three states. Similarly, fulfill can be a verb, but it is a less general one, as it basically means "resolve with something that I guarantee to not be a thenable".)

**Comment by cynthia** [comment]
@domenic would you have time to settle this sometime next week? I can block out time if needed. Just want to make sure that spec authors and web developers aren’t confused.

**Comment by domenic** [comment]
I'm a bit unsure what's unsettled here and what I would be needed for. https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md is pretty clear, as is Web IDL (e.g. https://heycam.github.io/webidl/#resolve)

**Comment by pthatcherg** [comment]
We have 4 instances where we use the word "resolved", so I'll just change those to "fulfilled" and I think we can close this issue.

**Comment by cynthia** [comment]
The settle bit was about the design principles issue (e.g. could use some advice) - thought this comment came from there, apparently not.
