### ISSUE TITLE
WHATWG streams

### ISSUE THREAD

**Issue by lgrahl** [WICG/web-transport#35]
I've experimented with [WHATWG streams](https://streams.spec.whatwg.org) for a few weeks. In my little demo it works pretty good now (apart from a few nits here and there that should be resolvable) and makes a much more composable API. Once more people start utilising WHATWG streams, piping from one stream to another or applying transformations can be made without much of a hassle. It also brings the advantage that data can be fed from the user application into the QUIC stream buffer directly without requiring to copy it.

I had to pause working on this as I need to work on my master thesis now. However, I don't want to hold back this idea any further and show you my current results. In case anyone else wants to jump in, feel free! Otherwise, I'll hopefully come back to this once I have some spare time.

Feedback welcome!

#### Spec

I've updated the spec but it's still work in progress. While methods and attributes of RTCQuicStream have been updated for WHATWG streams, general description and specification of the construction of a readable and a writable stream instance is still missing. However, you can have a look at the code if you want to see how I've written it for the demo.

The spec changes can be found [here](https://lgrahl.de/examples/ortc/#quicstream*) and [on GitHub](https://github.com/lgrahl/ortc/tree/quic-whatwg-streams).

Note: This was originally created for the ORTC Spec, so my spec changes may not be entirely accurate for this spec here.

#### Demo

The demo can be started [here](https://lgrahl.de/examples/ortc/demo) and the code can be found [here](https://github.com/lgrahl/ortc-streams-demo).

**Comment by pthatcherg** [comment]
I just landed https://github.com/WICG/web-transport/pull/16, which updates the explainer to use WHATWG streams.

**Comment by aboba** [comment]
Now that PR https://github.com/WICG/web-transport/issues/19 has been merged, can we close this issue?

**Comment by ExE-Boss** [comment]
@aboba I think you mean PR #46.

**Comment by lgrahl** [comment]
Yep.
