### ISSUE TITLE
Datagram support in Streams

### ISSUE THREAD

**Issue by aboba** [WICG/web-transport#39]
The examples in PR https://github.com/WICG/web-transport/pull/16/ have some issues with datagram boundaries.

Example: 
        `datagramWritableStream.getWriter().write(encodedGameState);`
        ....
        `reader.read();`

Is the expectation that `reader.read()` will preserve the datagram boundaries provided in `write(encodedGameState)`?

**Comment by pthatcherg** [comment]
Yes, it's no a ReadableStream of bytes.  It's a ReadableStream of datagrams (we can even wrap the datagram in an object if that makes us feel better).
