### ISSUE TITLE
Consider removing disableRetransmissions

### ISSUE THREAD

**Issue by vasilvv** [WICG/web-transport#42]
I believe we've discussed this before in person.  The feature, as it currently is in spec, is somewhat underspecified and we never actually heard from anyone about wanting to use that feature as-is.  Perhaps a good alternative would be export enough stats that the developer could make a good informed decision about cancellation themselves.

**Comment by aboba** [comment]
We did hear from a developer who wanted to be able to send large messages that might have limited time value (for robotics).

But even if we want to handle that use case I'm not clear that 'disableRetransmissions' is the way we would do it.  If the goal is just to allow a time-limited message, using a stream per message and setting a timer might be sufficient.  Or if the requirement is to be able to mimic functionality in `RTCDataChannel` then support for `maxRetransmissions` or `maxPacketLifetime` would make more sense. 

Related: https://github.com/w3c/webrtc-quic/issues/75

**Comment by lgrahl** [comment]
Fully agree with both of you. I considered this a hack from the beginning.

**Comment by pthatcherg** [comment]
Editor's discussion: let's go ahead and remove it for now.  Someone just needs to write the PR.

**Comment by kixelated** [comment]
:+1: for removing

It enabled a neat idea (streams emulating datagrams) but has limited use-cases now that there's proper datagram support.

I like the explicit ability to cancel QUIC streams (with a code). Exposing stream stats would allow developers to determine cancellation policies along with codes. Something simple such as both the current and acknowledged stream offset would allow a developer to implement `maxPacketLifetime` themselves.
