### ISSUE TITLE
References to QUIC in reusable interfaces

### ISSUE THREAD

**Issue by lgrahl** [WICG/web-transport#48]
`UnidirectionalStreamsTransport.createSendStream` and `BidirectionalStreamsTransport.createBidirectionalStream` refer to QUIC regarding the maximum amount of streams but shouldn't.

**Comment by pthatcherg** [comment]
Good catch.  In other places in the spec, we say things like "For QUIC, ...".  Perhaps we should do that here as well.

**Comment by pthatcherg** [comment]
Fixed in https://github.com/WICG/web-transport/pull/89.
