### ISSUE TITLE
Convergence with WebSocketStream

### ISSUE THREAD

**Issue by aboba** [WICG/web-transport#50]
[WebSocketStream API](https://docs.google.com/document/d/1La1ehXw76HP6n1uUeks-WJGFgAnpX2tCjKts7QFJ57Y/) defines `close()` and  `WebSocketCloseInfo` as follows:

```
void close(optional WebSocketCloseInfo closeInfo);

dictionary WebSocketCloseInfo {
  [Clamp] unsigned short code;
  USVString reason = "";
};
```

WebTransport defines `close()` and `WebTransportCloseInfo` this way: 

```
void close(WebTransportCloseInfo closeInfo);

dictionary WebTransportCloseInfo {
    unsigned short errorCode = 0;
    DOMString      reason = "";
};
```
Can we converge these?

**Comment by pthatcherg** [comment]
After talking to ricea, I think we basically decided not to any convergence, so I'm closing this issue.
