### ISSUE TITLE
should BidirectionalStreamsTransport createBidirectionalStream() take a SendStreamParameters (or something else)?

### ISSUE THREAD

**Issue by hugoArregui** [WICG/web-transport#64]
> Data is generally sent reliably, but retransmissions may be disabled or the stream may aborted to produce a form of unreliability. All stream data is encrypted and congestion-controlled.

but I don't see how retransmissions may be disabled in this case

**Comment by pthatcherg** [comment]
The parameters dictionary is currently empty.  We should probably add a BidirectionalStreamParameters dictionary to go along with SendStreamParameters.  But we should probably wait until there are parameters to add.
