### ISSUE TITLE
Beta testing availability?

### ISSUE THREAD

**Issue by endel** [WICG/web-transport#65]
Hi there, I understand the spec is still in somewhat early stages, I wonder if there's already plans on actual implementation inside any browser's beta channels? I'd love to play around with it as soon as it's available.

The web needs this. Thanks ❤️

**Comment by steveanton** [comment]
Hi Endel, thanks for your interest. There aren't any current prototypes of the latest WebTransport specification yet. However, you could try playing around with the RTCQuicTransport (which is similar) behind a flag in Chrome. See this [blog post](https://developers.google.com/web/updates/2019/01/rtcquictransport-api) for more details.

**Comment by pthatcherg** [comment]
You can track status at https://chromestatus.com/features/4854144902889472.  Implementation is in progress.
