### ISSUE TITLE
Why does the spec link to two versions of WEBIDL?

### ISSUE THREAD

**Issue by ricea** [WICG/web-transport#71]
Under "Conformance" there is a link to \[WEBIDL-1] which is https://www.w3.org/TR/2016/REC-WebIDL-1-20161215/. Other WebIDL links in the document go to \[WEBIDL] which is https://heycam.github.io/webidl/.

Is this intentional? What is the reason for it?

**Comment by vasilvv** [comment]
I forgot to make them consistent when I rewrote the spec into bikeshed.  Sent #72 to fix that.
