### ISSUE TITLE
WebTransport is both a mixin and an ordinary interface

### ISSUE THREAD

**Issue by ricea** [WICG/web-transport#73]
[`WebTransport`](https://wicg.github.io/web-transport/#webtransport) is declared as a mixin with `interface mixin WebTransport` and used as a mixin in `QuicTransportBase includes WebTransport;`. However, it is also used as an interface in [`WebTransportStream`](https://wicg.github.io/web-transport/#webtransportstream): `readonly attribute WebTransport transport;`.

**Comment by pthatcherg** [comment]
It seems l like our two options are:

A.  Change it to "readonly attribute WebTransport transport" and say in text "must include WebTransport mixin"

B.  Remove it, like we removed .streamId.

I'm kind of thinking removing it would be nice.  Then we could remove "interface WebTransportStream"  entirely.

**Comment by pthatcherg** [comment]
I made https://github.com/WICG/web-transport/pull/84 to do option B (removing it).
