### ISSUE TITLE
QuicTransportBase is not subclassable by user code

### ISSUE THREAD

**Issue by ricea** [WICG/web-transport#75]
QuicTransportBase cannot be subclassed from JavaScript because it has no constructor. It's usually considered bad practice in the web platform to have classes that are not subclassable.

Since it only provides one method in addition to the mixins it uses, it probably is not needed at all. Any variants could just use the same mixins.

**Comment by vasilvv** [comment]
To add some context, the goal of that class is mostly to provide a shared base for QuicTransport and [RTCQuicTransport](https://w3c.github.io/webrtc-quic/#rtcquic-transport*).  I think making it a mixin would make sense (WebIDL does not allow including mixins into mixins, but we could always just specify those as extra text).

**Comment by ricea** [comment]
It sounds like the benefit is only to the specifications authors. I think by the principle that "users > developers > browser authors > specification authors" we should remove it.

See also https://w3ctag.github.io/design-principles/#constructors.

**Comment by pthatcherg** [comment]
I'm in favor of removing QuicTransportBase and duplicating the needed text in WebRTC-QUIC.
