### ISSUE TITLE
Can `onerror` fire multiple times?

### ISSUE THREAD

**Issue by ricea** [WICG/web-transport#81]
If not it should be a promise, as per https://w3ctag.github.io/design-principles/#one-time-events.

**Comment by yutakahirano** [comment]
+1

**Comment by yutakahirano** [comment]
Something like this?

```
readonly attribute Promise<WebTransportCloseInfo> closed;
```

**Comment by steveanton** [comment]
Yeah, I think this should be changed to a promise.
