### ISSUE TITLE
Table of Contents is Gone

### ISSUE THREAD

**Issue by shampson** [WICG/web-transport#9]
I think this happened in the latest merged PRs. The Http3Transport is probably the culprit:
https://github.com/pthatcherg/web-transport/pull/7

https://pthatcherg.github.io/web-transport/

**Comment by aboba** [comment]
@shampson  There is an error in the references, introduced in the recently merged PRs.  I have submitted a fix:  https://npm.pkg.github.com/pthatcherg/web-transport/pull/11

**Comment by shampson** [comment]
Resolved.
