### ISSUE TITLE
Flow control for creating new streams

### ISSUE THREAD

**Issue by aboba** [WICG/web-transport#98]
vasilvv opened this issue on Feb 10, 2019
Moved from https://github.com/w3c/webrtc-quic/issues/112

In general, I like the read/write API for QUIC stream data (though I think there should be a better story for controlling send buffer size, etc).  In IETF QUIC, opening new streams is flow controlled in the same way sending data on an individual stream is, but the behavior of API seems to be different: it seems to imply the streams are created immediately when the connection is fully open.  There is a similar discrepancy in terms of reading: the client can choose when to read data from streams, but has to be event-notified about when a new stream is received.  I suggest making receiving incoming streams pull-based (i.e. you call receiveStream() and get a promise that's fulfilled when a new stream is received).

**Comment by vasilvv** [comment]
Fixed by the streams refactor.
