### ISSUE TITLE
Stats, there got to be stats...

### ISSUE THREAD

**Issue by aboba** [WICG/web-transport#99]
vr000m opened this issue on Sep 26, 2018
Moved from https://github.com/w3c/webrtc-quic/issues/66

What do we want to measure, what measurements can we expose from the underlying stack.

counters: bytes, messages, streamsOpened (*state), round trip time, losses/timeouts/resets?
or does the application keep track of bytesSent/received?

**Comment by vasilvv** [comment]
We currently have https://wicg.github.io/web-transport/#quic-transport-stats

Let's close this for now and open issues for individual things that people want to be added to QuicTransportStats.
